Daniel to main
DovaX/pgwidget pull request #25
Opened 2022-12-05 15:10 UTC by YoungMasterGandalf

2022-12-05 15:45 UTC, DovaX requested changes

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +                    label._draw_cursor(screen)
auto_draw_cursor - please add description what this means

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +                    label._draw_cursor(screen)
docstring

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            self.shown_cursor_offset_index = len(self.shown_text_rows[self.shown_cursor_row_index])
change to camera offset

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            self.shown_cursor_offset_index = len(self.shown_text_rows[self.shown_cursor_row_index])
change to camera offset

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            self.cursor_row_index = self.shown_cursor_row_index + self.shown_text_first_line_index
change to camera offset

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            # init_height = self.get_text_pixel_height(self.shown_text_first_line_index - 1) if self.shown_text_first_line_index > 0 else 0
remove

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            text_height = sum(text_rows_heights)
This will make performance dramatically slower - can we put there a constant or evaluate myfont.size just once?

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            text_height = sum(text_rows_heights)
better to not use myfont.size at all

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            self.shown_text_rows = self.shown_text_rows[self.shown_text_first_line_index: self.shown_text_last_line_index + 1]
replace with camera offset

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            self.shown_cursor_row_index = self._cursor_row_index - self.shown_text_first_line_index
replace with camera offset

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        if self.shown_cursor_row_index is not None and 0 <= self.shown_cursor_row_index < len(self.shown_text_rows):
0 <= self.shown_cursor_row_index < len(self.shown_text_rows)
????? what's wrong here? :)

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        if self.shown_cursor_row_index is not None and 0 <= self.shown_cursor_row_index < len(self.shown_text_rows):
please also add a comment explaining the condition here

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        if self.shown_cursor_row_index is not None and 0 <= self.shown_cursor_row_index < len(self.shown_text_rows):
do the same with other occurence of the same "if" above

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +            if len(self._text.split("\n")) != len(text.split("\n")):
potential problems on linux/mac ("\r\n" problem?)

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        self.refresh_shown_text()
Discuss these two properties with dominik -> are they really needed?

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        self._shown_text_last_line_index = len(self.shown_text.split('\n'))
are both needed?

2022-12-05 15:45 UTC, DovaX commented on pgwidget/pgwidget_core.py
> +        self._shown_text_last_line_index = len(self.shown_text.split('\n'))
+ replace with camera offset

2022-12-05 21:57 UTC, YoungMasterGandalf commented on pgwidget/pgwidget_core.py
> +            if len(self._text.split("\n")) != len(text.split("\n")):
Haven't encountered any on Linux.

2022-12-07 20:21 UTC, DovaX approved these changes

2022-12-07 20:21 UTC, merged